Add compact search's version for mobile&tablet and fix navbar
comindware/core-ui pull request #1165
Opened 2020-01-16 13:29 UTC by li7a

2020-01-17 07:56 UTC, PavelKoroteev requested changes

2020-01-17 07:56 UTC, PavelKoroteev commented on resources/styles/themes/main/styles.css
> +
Линтер разрешил?

2020-01-17 07:56 UTC, PavelKoroteev commented on resources/styles/themes/main/styles.css
> +    padding: 0 15px;
Перемещение padding а нужно отменить.

2020-01-17 07:56 UTC, PavelKoroteev commented on resources/styles/themes/theme.css
> -/* stylelint-disable */
Не нужно удалять, скорее всего

2020-01-17 07:56 UTC, PavelKoroteev commented on src/views/SearchBarView.ts
> +            const value = this.ui.input.val('');
Не используется?

2020-01-17 07:56 UTC, PavelKoroteev commented on src/views/SearchBarView.ts
> +                this.__toggleClearIcon();
Если не searchOnEnter, то не надо делать toggleClearIcon ?

2020-01-17 07:56 UTC, PavelKoroteev commented on src/views/SearchBarView.ts
> -            this.__search();
search же нужен, если не search не на Enter.

2020-01-27 16:38 UTC, PavelKoroteev approved these changes

2020-01-28 08:46 UTC, stasguryev commented on src/views/SearchBarView.ts
> +        const currentClassName = this.__getClassName({ searchBarIsOpen: true });
classes.closed или classes.static добавленные в onRender потеряются вроде

2020-01-28 17:04 UTC, merged