Fix filter on enter key
comindware/core-ui pull request #1198
Opened 2020-02-07 18:49 UTC by li7a

2020-02-10 08:40 UTC, li7a commented
Пока не заливать. Допил

2020-02-10 11:40 UTC, PavelKoroteev requested changes

2020-02-10 11:40 UTC, PavelKoroteev commented on src/form/editors/DatalistEditorView.ts
> +            this.trigger('apply:filter:onEnter');
Datalist не должен знать о фильтрах

2020-02-11 16:26 UTC, li7a commented
исправлено

2020-02-12 08:13 UTC, PavelKoroteev requested changes

2020-02-12 08:13 UTC, PavelKoroteev commented on src/form/editors/DatalistEditorView.ts
> +            if (!this.panelCollection.lastPointedModel?.selected) {
Оptional chaining или не нужен или не сработает так, как подразумевается

2020-02-12 11:31 UTC, PavelKoroteev approved these changes

2020-02-12 11:48 UTC, PavelKoroteev approved these changes

2020-02-12 11:49 UTC, merged