Add option icon for datalist
comindware/core-ui pull request #1229
Opened 2020-03-02 11:15 UTC by Tonypz

2020-03-05 09:53 UTC, PavelKoroteev requested changes

2020-03-05 09:53 UTC, PavelKoroteev commented on src/form/editors/DatalistEditorView.ts
> +                    metaIcons: this.options.metaIcons || {}
в дефолтные опции metaIcons: Core.meta.contextIconType,

2020-03-05 11:11 UTC, Tonypz commented on src/form/editors/DatalistEditorView.ts
> +                    metaIcons: this.options.metaIcons || {}
поправил

2020-03-05 11:11 UTC, Tonypz commented on src/form/editors/DatalistEditorView.ts
> +                    metaIcons: this.options.metaIcons || {}
> в дефолтные опции metaIcons: Core.meta.contextIconType,

поправил

2020-03-12 11:30 UTC, PavelKoroteev approved these changes

2020-03-12 11:33 UTC, merged