[#172805] HeaderGrid: fix resize last column
comindware/core-ui pull request #1238
Opened 2020-03-06 08:03 UTC by Tonypz

2020-03-06 08:13 UTC, stasguryev commented on src/list/views/header/GridHeaderView.ts
> +        if (delta === 0) {
delta === 0 || e.pageX === window.innerWidth

2020-03-06 08:43 UTC, Tonypz commented on src/list/views/header/GridHeaderView.ts
> +        if (delta === 0) {
> delta === 0 || e.pageX === window.innerWidth

только наверно && ?

2020-03-06 09:58 UTC, PavelKoroteev requested changes

2020-03-06 09:58 UTC, PavelKoroteev commented on src/list/views/header/GridHeaderView.ts
> +        if (delta === 0) {
Да

2020-03-06 12:15 UTC, stasguryev approved these changes

2020-03-10 15:44 UTC, PavelKoroteev requested changes

2020-03-10 15:44 UTC, PavelKoroteev commented on src/list/views/header/GridHeaderView.ts
> +            this.__setLastColumnWidth(index, deltaOffScreenWidth, deltaX);
LastScreenColumnWidth ?

2020-03-10 15:44 UTC, PavelKoroteev commented on src/list/views/header/GridHeaderView.ts
> +            this.deltaLastColumn = 0;
Сбрасывать в блоке else, и возможно, что не сбрасывать.

2020-03-26 14:11 UTC, closed without merging