[#479812] Codemirror: fix call local hints for N3
comindware/core-ui pull request #1259
Opened 2020-03-20 11:21 UTC by Tonypz

2020-03-20 11:26 UTC, stasguryev commented on src/form/editors/impl/codeEditor/Constants.js
> +    getOptionsCodemirror: {
why get?

2020-03-20 11:29 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +            (prefix.description = prefix.description ? prefix.description : '-'), (prefix.icons = contextIconType.case);
,  => ;

2020-03-20 11:30 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +        const getOptions = {};
resultOptions

2020-03-20 11:46 UTC, PavelKoroteev requested changes

2020-03-20 11:46 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                return true;
Что означает true ?

2020-03-20 11:46 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                if (!arrNameVariablesNotation3.includes(variable.substr(1)) && variable.length > 1) {
Оригинальный способ проверить на пустую строку)

2020-03-20 11:46 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +        const getOptions = {};
getOptions должно быть строкой. Назови resultOptions (ну или ещё как-нибудь на своё усмотрение, но не именем метода)

2020-03-20 12:03 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +            (prefix.description = prefix.description ? prefix.description : '-'), (prefix.icons = contextIconType.case);
=> ----> ---->

2020-03-20 12:19 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                if (!arrNameVariablesNotation3.includes(item.substr(1)) && nameItem) {
item.substr(1) => nameItem

2020-03-20 12:20 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                if (!arrNameVariablesNotation3.includes(item.substr(1)) && nameItem) {
item.substr(1) ----> nameItem

2020-03-20 12:21 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +            const beforeSymbolQuestionMark = valueLine[ch - 2];
constants

2020-03-20 13:45 UTC, PavelKoroteev approved these changes

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
>          if (isScriptMode) {
siwtch case

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +        if (mode === constants.mode.script) {
siwtch case

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +            this.CSharpInfoList = null;
if mode !== script ?

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +            const filterWithDelimiter = valueLine.slice(0, column).match(/.(\w*)$/);
const regex

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +            this.codemirror.showHint({ hint: this.__showHintsN3_ctr_spcase });
__showHintsN3_ctr_spcase  ?

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +        return subStringForFind.includes(constants.activeSymbolNotation3.comment);
starts with?

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                    resultOptions[constants.optionsCodemirror.valueLine] = this.codemirror.getLine(cursor.line);
const this.codemirror.getLine(cursor.line)

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                        .includes('(');
const '('

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                        .slice(cursor.ch, lineLength)
slice => substring?

2020-03-23 14:38 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +        if (isSymbolQuestionMark) {
switchCase

2020-03-23 16:53 UTC, PavelKoroteev requested changes

2020-03-23 16:53 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                    return filterName;
return filterName есть во всех ветках if ?

2020-03-23 16:53 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +            this.codemirror.showHint({ hint: this.__showHintsN3_ctr_spcase });
Почти по БЭМу)

2020-03-23 16:53 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                        .slice(cursor.ch, lineLength)
Второй аргумент не обязательный у slice.

2020-04-15 09:25 UTC, Tonypz commented
Duplicate

2020-04-15 09:25 UTC, closed without merging