[#476633] Set init widt on columns (personal/system config)
comindware/core-ui pull request #1267
Opened 2020-03-25 12:19 UTC by Tonypz

2020-03-25 12:21 UTC, stasguryev commented on src/components/treeEditor/controllers/DiffController.ts
> +                const column = collection.get(key);
if (!column) {return }

2020-03-25 12:22 UTC, stasguryev commented on src/list/views/GridView.ts
> +            this.headerView.__updateColumnAndNeighbourWidths(columnsCollection.at(index));
private!

2020-03-25 12:25 UTC, PavelKoroteev requested changes

2020-03-25 12:25 UTC, PavelKoroteev commented on src/list/views/GridView.ts
> +            this.headerView.__setColumnWidth(index, newColumnWidth);
Приватные методы не стоит использовать извне, сам обработчик лучше перенести в headerView, там можно их исползовать.

2020-03-25 12:25 UTC, PavelKoroteev commented on src/list/views/GridView.ts
> +            this.headerView.__updateColumnAndNeighbourWidths(columnsCollection.at(index));
columnsCollection.at(index) ---> model

2020-03-25 12:25 UTC, PavelKoroteev commented on src/list/views/GridView.ts
> +            const newColumnWidth = model.get('width');
newColumnWidth вторым аргументом приезжает, можно его использовать.

2020-03-25 12:53 UTC, Tonypz commented on src/list/views/GridView.ts
> +            const newColumnWidth = model.get('width');
поправил

2020-03-25 12:53 UTC, Tonypz commented on src/list/views/GridView.ts
> +            this.headerView.__setColumnWidth(index, newColumnWidth);
поправил

2020-03-25 12:53 UTC, Tonypz commented on src/list/views/GridView.ts
> +            this.headerView.__updateColumnAndNeighbourWidths(columnsCollection.at(index));
поправил

2020-03-25 12:54 UTC, Tonypz commented on src/components/treeEditor/controllers/DiffController.ts
> +                const column = collection.get(key);
column определяется в цикле for, если в текущей column undefined  то в следующих итерациях column может быть опредлен

2020-03-25 12:57 UTC, stasguryev commented on src/components/treeEditor/controllers/DiffController.ts
> +                const column = collection.get(key);
и как это отменяет ранний return?

2020-03-25 13:00 UTC, PavelKoroteev requested changes

2020-03-25 13:00 UTC, PavelKoroteev commented on src/list/views/header/GridHeaderView.ts
> +        });
!

2020-03-25 13:00 UTC, PavelKoroteev commented on src/list/views/header/GridHeaderView.ts
> +            this.__updateColumnAndNeighbourWidths(model);
метод приниает HTMLElement, а мы прокидываем модель?

2020-03-25 13:01 UTC, Tonypz commented on src/components/treeEditor/controllers/DiffController.ts
> +                const column = collection.get(key);
+

2020-03-26 08:50 UTC, PavelKoroteev requested changes

2020-03-26 08:50 UTC, PavelKoroteev commented on src/components/treeEditor/controllers/DiffController.ts
> +                if (column && (currentIndexColumn !== newIndexColumn)) {
на column уже проверил на строке 199.

2020-03-26 08:50 UTC, PavelKoroteev commented on src/components/treeEditor/controllers/DiffController.ts
> +                if (column) {
На column уже проверил на строке 199.

2020-03-26 08:51 UTC, Tonypz commented on src/components/treeEditor/controllers/DiffController.ts
> +                if (column) {
круто, не заметил

2020-03-26 09:55 UTC, PavelKoroteev approved these changes

2020-03-26 09:55 UTC, merged