[#476633] GridHeaderView: fix column width in model
comindware/core-ui pull request #1281
Opened 2020-04-01 14:15 UTC by Tonypz

2020-04-01 14:23 UTC, PavelKoroteev approved these changes

2020-04-01 16:19 UTC, PavelKoroteev commented on src/list/views/header/GridHeaderView.ts
> +            this.options.columnsCollection.at(i).set('width', width);
!

2020-04-01 18:02 UTC, PavelKoroteev requested changes

2020-04-01 18:02 UTC, PavelKoroteev commented on src/list/views/header/GridHeaderView.ts
> +            this.options.columnsCollection.at(i).set('width', width);
Это же временные значения, я бы не сохранял их в модель, с возможностью сохранить на сервере по кнопке.

2020-04-02 15:12 UTC, Tonypz commented on src/list/views/header/GridHeaderView.ts
> +            this.options.columnsCollection.at(i).set('width', width);
поправил

2020-04-06 12:04 UTC, PavelKoroteev approved these changes

2021-11-10 16:22 UTC, closed without merging