[#481816] CodeEditor: consecutive call showHint
comindware/core-ui pull request #1283
Opened 2020-04-03 07:53 UTC by Tonypz

2020-04-03 08:00 UTC, PavelKoroteev requested changes

2020-04-03 08:00 UTC, PavelKoroteev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                return;
return ---> break;

2020-04-06 12:01 UTC, PavelKoroteev approved these changes

2020-04-07 08:49 UTC, stasguryev commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +                // eslint-disable-next-line no-case-declarations
?

2020-04-09 10:02 UTC, merged