[#484823] Fix open disabled tabs
comindware/core-ui pull request #1299
Opened 2020-04-15 15:44 UTC by annamitr

2020-04-15 15:47 UTC, Tonypz approved these changes

2020-04-15 15:51 UTC, PavelKoroteev requested changes

2020-04-15 15:51 UTC, PavelKoroteev commented on src/layout/tabLayout/HeaderMenuPanelItemView.ts
> +        click: '__onClick'
Клик же и так работает, зачем добавлять events ?

2020-04-16 15:30 UTC, annamitr commented on src/layout/tabLayout/HeaderMenuPanelItemView.ts
> +        click: '__onClick'
Исправила)

2020-04-17 07:59 UTC, PavelKoroteev approved these changes

2020-04-17 07:59 UTC, merged