Merge branch '2.0/release' into 2.1/release
comindware/core-ui pull request #1374
Opened 2020-07-19 22:19 UTC by stasguryev

# Conflicts:
#	.eslintrc.js
#	.travis.yml
#	demo/package-lock.json
#	demo/package.json
#	package-lock.json
#	package.json
#	resources/styles/codemirror.css
#	resources/styles/dropdown.css
#	resources/styles/gallery.css
#	resources/styles/list.css
#	resources/styles/themes/main/styles.css
#	resources/styles/themes/new/styles.css
#	resources/styles/themes/theme.css
#	src/Meta.ts
#	src/collections/VirtualCollection.ts
#	src/components/treeEditor/controllers/DiffController.ts
#	src/form/editors/ComplexEditorView.js
#	src/form/editors/DatalistEditorView.ts
#	src/form/editors/base/MarionetteEditorPrototype.ts
#	src/form/editors/impl/codeEditor/Constants.js
#	src/form/editors/impl/codeEditor/services/CmwCodeAssistantServices.js
#	src/form/editors/impl/codeEditor/templates/codeEditor.html
#	src/form/editors/impl/codeEditor/views/CodemirrorView.js
#	src/form/editors/impl/datalist/views/ReferenceListWithSubtextItemView.js
#	src/layout/tabLayout/TabHeaderView.ts
#	src/list/CellViewFactory.ts
#	src/list/meta.ts
#	src/list/templates/compositeUserCell.html
#	src/list/views/CollectionView.ts
#	src/list/views/GridView.ts
#	src/list/views/RowView.ts
#	src/list/views/header/GridHeaderView.ts
#	src/views/SearchBarView.ts
#	src/views/SplitPanelResizer.js
#	src/views/SplitPanelView.js
#	tests/specs/form/DatalistEditorView.spec.js

2020-07-20 13:11 UTC, pablo3443 requested changes

2020-07-20 13:11 UTC, pablo3443 commented on src/list/CellViewFactory.ts
> +import Backbone from 'backbone';
нужно удалить эти 3 импорта

2020-07-20 13:11 UTC, pablo3443 commented on src/list/CellViewFactory.ts
> +        <span class="composite-cell__count">+{{count}}</div>
оставить span

2020-07-20 13:11 UTC, pablo3443 commented on dist/localization/localization.ru.json
> -{"CORE":"core","CORE.COMMON":"common","CORE.COMMON.LOADING":"Загрузка...","CORE.COMMON.NOTSET":"Не задано","CORE.COMMON.SAVE":"Сохранить","CORE.DEMO":"demo","CORE.DEMO.CASES":"cases","CORE.DEMO.CASES
локализацию наверно не надо коммитить

2020-07-20 13:11 UTC, pablo3443 commented on resources/styles/form.css
> +    flex: none;
удалить

2020-07-20 13:11 UTC, pablo3443 commented on resources/styles/dropdown.css
> +.core-ui__global-popup-region > .dropdown__wrp_down
не уверен, что этот файл нужно коммитить

2020-07-20 13:11 UTC, pablo3443 commented on resources/styles/list.css
> +    height: auto !important;
это скорее всего не надо коммитить

2020-07-20 13:11 UTC, pablo3443 commented on resources/styles/list.css
> +    display: inline-flex;
стили у этого класса не надо коммитить

2020-07-20 13:11 UTC, pablo3443 commented on src/collections/VirtualCollection.ts
>  import _ from 'underscore';
удалить импорт

2020-07-20 13:11 UTC, pablo3443 commented on src/form/editors/DatalistEditorView.ts
> +        this.debouncedFetchUpdateFilter(undefined, { isSearch: true });
это правильно работает?

2020-07-20 13:11 UTC, pablo3443 commented on src/form/editors/DatalistEditorView.ts
> +    __getDisplayText(value, displayAttribute = this.options.displayAttribute): string {
тесты добавить наверно надо

2020-07-20 13:11 UTC, pablo3443 commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +        if (token && token.type === 'string') {
можно в одну строчку

2020-07-20 13:11 UTC, pablo3443 commented on src/form/editors/impl/codeEditor/views/CodemirrorView.js
> +        if (this.options.showMode === showModes.button && this.valueAfterMaximize !== this.codemirror.getValue()) {
можно на askYesNo

2020-07-20 13:11 UTC, pablo3443 commented on src/form/editors/impl/radioGroup/templates/radioButton.hbs
> +<span class="radiobutton-text" title="{{displayText}}">{{#if displayHtml}}{{{displayHtml}}}{{else}}{{displayText}}{{/if}}</span>
тут нужно отступы сделать и перенести строки, чтобы читалось лучше

2020-07-20 13:11 UTC, pablo3443 commented on src/list/CellViewFactory.ts
> +                formattedValues = value.map(v => ({ value }));
не менять эту строчку в value передаётся массив, а не элемент

2020-07-20 13:11 UTC, pablo3443 commented on src/list/CellViewFactory.ts
> +                formattedValues = value.map(v => ({ value }));
и возможно оставить строку по дефолту

2020-07-20 13:11 UTC, pablo3443 commented on src/list/CellViewFactory.ts
> +    __getFormattedReferenceValue({ value, column }: ValueFormatOption) {
возможно эту функцию не нужно менять

2020-07-20 13:11 UTC, pablo3443 commented on src/list/views/RowView.ts
> +            setTimeout(
?

2020-07-20 13:11 UTC, pablo3443 commented on src/services/MobileService.ts
> +        this.isIOS = /iPhone|iPad|iPod/i.test(userAgent);
это правда работает?

2020-07-20 13:11 UTC, pablo3443 commented on src/services/RoutingService.js
> +        WindowService.closePopup();
наверно не нужно коммитить этот файл

2020-07-21 09:07 UTC, Tonypz approved these changes

2020-07-21 20:50 UTC, merged