[#88094] Fix localization on theme palette
comindware/core-ui pull request #1406
Opened 2020-09-10 15:54 UTC by AlexanderAMalinov

2020-09-10 18:54 UTC, pablo3443 requested changes

2020-09-10 18:54 UTC, pablo3443 commented on localization/localization.n3
> +<http://comindware.com/text/core/form/editors/memberSplit#choose> a l10n:Resource; l10n:descr ""; l10n:isLocalizable true; l10n:needsReview true; l10n:createdBy "Alexander Malinov"; l10n:modifiedBy "
надо ноды создать в color-picker

2020-09-11 08:21 UTC, AlexanderAMalinov commented on localization/localization.n3
> +<http://comindware.com/text/core/form/editors/memberSplit#choose> a l10n:Resource; l10n:descr ""; l10n:isLocalizable true; l10n:needsReview true; l10n:createdBy "Alexander Malinov"; l10n:modifiedBy "
не понимаю)

2020-09-11 11:51 UTC, AlexanderAMalinov commented on localization/localization.n3
> +<http://comindware.com/text/core/form/editors/memberSplit#choose> a l10n:Resource; l10n:descr ""; l10n:isLocalizable true; l10n:needsReview true; l10n:createdBy "Alexander Malinov"; l10n:modifiedBy "
поправил

2020-09-11 15:01 UTC, merged