2.1/merge updates2.0
comindware/core-ui pull request #1433
Opened 2020-10-20 15:51 UTC by stasguryev

2020-10-20 17:01 UTC, pablo3443 requested changes

2020-10-20 17:01 UTC, pablo3443 commented on src/services/RoutingService.js
> +        shouldCheckUrl = true;
я бы убрал checkUrl

2020-10-20 17:01 UTC, pablo3443 commented on src/list/views/RowView.ts
> +        switch (column.dataType || column.type) {
а какое поведение здесь будет?
Он не будет сравнивать по column.type всегда даже когда есть column.dataType
И может быть тут лучше if includes

2020-10-21 08:42 UTC, stasguryev commented on src/services/RoutingService.js
> +        shouldCheckUrl = true;
не в рамках мерджа

2020-10-21 08:42 UTC, stasguryev commented on src/list/views/RowView.ts
> +        switch (column.dataType || column.type) {
Он не будет сравнивать по column.type только если есть column.dataType

2020-10-21 08:43 UTC, merged