[#533941] Fix save width of grid columns in personal configuration
comindware/core-ui pull request #1439
Opened 2020-10-29 16:03 UTC by AlexanderAMalinov

2020-10-29 16:18 UTC, pablo3443 requested changes

2020-10-29 16:18 UTC, pablo3443 commented on src/components/treeEditor/TreeEditor.ts
> +import { TTreeEditorOptions, GraphModel, NodeConfig } from './types';
?

2020-10-29 16:18 UTC, pablo3443 commented on src/components/treeEditor/TreeEditor.ts
> +        this.controller.reqres.request('treeEditor:setWidgetConfig', widgetId, config);
reqres лучше не использовать в коре

2020-10-30 08:20 UTC, AlexanderAMalinov commented on src/components/treeEditor/TreeEditor.ts
> +        this.controller.reqres.request('treeEditor:setWidgetConfig', widgetId, config);
поправил

2020-10-30 16:57 UTC, pablo3443 approved these changes

2020-10-30 16:58 UTC, merged