[#179570][#417139] Fix input maxlength and min/max in IE
comindware/core-ui pull request #1450
Opened 2020-11-18 14:13 UTC by vld-blv

2020-11-19 21:08 UTC, pablo3443 requested changes

2020-11-19 21:08 UTC, pablo3443 commented on src/form/editors/NumberEditorView.js
> +        let value = event.target.value;
почему let?

2020-11-19 21:08 UTC, pablo3443 commented on src/form/editors/NumberEditorView.js
> +            const input = this.ui.input;
надо onChange переиспользовать

2020-11-20 07:03 UTC, vld-blv commented on src/form/editors/NumberEditorView.js
> +        let value = event.target.value;
Если value > max, то value сразу же перезаписывается, 142 строка

2020-11-23 11:38 UTC, pablo3443 approved these changes

2020-11-25 15:39 UTC, vld-blv commented on src/form/editors/NumberEditorView.js
функции __onChange и __onBlur наверное можно убрать? Сейчас то же самое происходит непосредственно в __keyup и сразу применяются (при необходимости) значения min и max. Плюс __keyup корректно отрабатывает в IE, поэтому нет необходимости в дополнительной проверке

2020-11-25 15:42 UTC, vld-blv commented on src/form/editors/NumberEditorView.js
> +        if ((parsed === 0 || parsed === null) && value[0] === '-') {
Проверка parsed === null нужна, чтобы можно было вводить отрицательное число, так как this.__parse('-') возвращает null

2020-11-25 15:46 UTC, vld-blv commented on src/form/editors/NumberEditorView.js
А нет, нельзя. При min > 0 нельзя сравнивать min с вводимым значением в __keyup

2020-11-27 08:07 UTC, merged