[#669232] Add wizard
comindware/core-ui pull request #1560
Opened 2021-04-23 13:08 UTC by vld-blv

2021-04-23 15:01 UTC, pablo3443 requested changes

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/behaviors/LayoutBehavior.ts
> +        if (this.view.setEnablement) {
setEnablement такое слово существует?

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/button/ButtonView.js
> +            if (typeof options.isEnabled === 'function') {
а если не функция?

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/button/ButtonView.js
> +                isEnabled ? el.removeClass(classes.DISABLED) : el.addClass(classes.DISABLED);
Через if

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/button/ButtonView.js
> +                const el = this.$el;
зачем лишняя переменная?

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/button/ButtonView.js
> +            isNext: this.options.iconClass === 'chevron-right'
откуда взялось?

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/button/button.hbs
> +    {{#if isNext}}
в чем разница?
можно более понятно шаблон упростить

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/popup/PopupView.ts
> +            this.ui.window.css('background-color', this.options.bgc);
bgc плохое название

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/resources/wizard.css
> +    transform: skewX(-35deg);
??

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/resources/wizard.css
> +    transform: skewX(35deg);
??

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/wizard/WizardHeaderItemView.ts
> +        const stepNumber = this.model.get('stepNumber');
для свойство модели не нужен templateContext

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/wizard/WizardHeaderItemView.ts
> +        this.el.setAttribute('id', this.model.id);
attributes?

2021-04-23 15:01 UTC, pablo3443 commented on src/layout/wizard/WizardHeaderItemView.ts
> +    attributes() {
зачем нужны?

2021-04-23 15:07 UTC, pablo3443 requested changes

2021-04-23 15:07 UTC, pablo3443 commented on src/layout/wizard/WizardView.ts
> +            if (stepModel.isShow == null) {
тут какая-то магия

2021-04-26 08:02 UTC, vld-blv commented on src/layout/resources/wizard.css
> +    transform: skewX(-35deg);
![image](https://user-images.githubusercontent.com/55315304/116049154-a50b3f80-a67e-11eb-97be-22ddba034048.png)
Трансформ нужен, чтобы наклонить грани шагов в хедере

2021-04-26 08:04 UTC, vld-blv commented on src/layout/resources/wizard.css
> +    transform: skewX(35deg);
Здесь делаю наклон в сторону, обратную наклону стороны табов, чтобы получить квадратную область и закрасить получившиеся в результате наклона первого и последнего табов пробелы

2021-04-26 10:49 UTC, stasguryev commented on src/layout/button/ButtonView.js
> +                isEnabled ? el.removeClass(classes.DISABLED) : el.addClass(classes.DISABLED);
classList.toggle

2021-04-26 10:52 UTC, stasguryev commented on src/layout/popup/PopupView.ts
> +            isResizerHidden: this.options.isResizerHidden,
fullscreenToggleDisabled

2021-04-26 10:54 UTC, stasguryev commented on src/layout/button/button.hbs
> +    {{#unless isNext}}
обычная кнопка ничего не знает про next и так далее, либо сделать на ее основе свою, либо через css

2021-04-26 10:56 UTC, stasguryev commented on src/layout/resources/wizard.css
> +    background-color: #f5f5f5;
цвета из переменных

2021-04-26 10:57 UTC, stasguryev commented on src/layout/wizard/StepHeaderView.ts
> +        this.StepHeadersView = new StepHeadersView({
stepHeadersView

2021-05-11 16:28 UTC, pablo3443 requested changes

2021-05-11 16:28 UTC, pablo3443 commented on src/form/editors/RadioGroupEditorView.js
> +            return { isEmptyGroup: !(this.options.radioOptions && this.options.radioOptions.length) };
Нужно использовать emptyView

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/button/ButtonView.js
> +        this.on('change:enabled', (view, state) => view.$el.toggleClass(classes.DISABLED, !state));
это наверно лучше в LayoutBehavior прописать

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/button/ButtonView.js
> +            this.handlerResult = this.options.handler(this.options.context);
проверка на функцию?

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/button/ButtonView.js
> +            this.ui.btn.css('flex-direction', 'row-reverse');
через класс

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/resources/wizard.css
> +.layout__wizard__header-view ul {
может убрать ul оттуда просто

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/resources/wizard.css
> +    color: black;
из темы?

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/resources/wizard.css
> +    background-color: #f5f5f5;
из темы

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/resources/wizard.css
> +.layout__wizard__header-view-item:hover {
курсор и так появляется только на ховере

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/resources/wizard.css
> +    align-self: unset !important;
!important не стоит использовать

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/wizard/WizardHeaderItemView.ts
> +// @flow
зачем flow

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/wizard/WizardView.ts
> +        const classList = [];
зачем массив делать?

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/wizard/WizardView.ts
> +        const buttons = step.get('buttons').map(
использовать CollectionView

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/wizard/WizardView.ts
> +    async __generateButtonActions(step: Backbone.Model) {
?

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/wizard/templates/stepHeader.hbs
> +<ul class="js-tabs-headers-region"></ul>
почему ul?

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/wizard/WizardHeaderItemView.ts
> +    tagName: 'li',
почему li?

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/wizard/WizardView.ts
> +        helpers.assertArgumentNotFalsy(stepId, 'stepId');
??

2021-05-11 16:28 UTC, pablo3443 commented on src/layout/wizard/WizardView.ts
> +        const stepModel = this.__stepsCollection.find(x => x.id === stepId);
для CollectionVeiw можно использовать findByModel и другие

2021-05-12 08:14 UTC, stasguryev commented on src/layout/popup/PopupView.ts
> +            this.ui.window.css('background-color', this.options.backgroundColor);
class

2021-05-12 08:16 UTC, stasguryev commented on src/layout/resources/wizard.css
> +    transform: skewX(-35deg);
IE?

2021-05-13 11:37 UTC, vld-blv commented on src/layout/wizard/templates/stepHeader.hbs
> +<ul class="js-tabs-headers-region"></ul>
Обычно для элементов навигации используются именно ul, разве нет?

2021-05-13 12:09 UTC, vld-blv commented on src/layout/resources/wizard.css
> +.layout__wizard__header-view-item:hover {
В хедерах есть текст, соответственно, курсор принимает вид курсора при работе с текстом, поэтому я явно прописываю default. Курсор не pointer в данном случае, потому что хедеры не кликабельны, навигация происходит только с помощью кнопок

2021-05-13 15:26 UTC, vld-blv commented on src/layout/button/ButtonView.js
> +        this.on('change:enabled', (view, state) => view.$el.toggleClass(classes.DISABLED, !state));
LayoutBehavior только устанавливает enabled и тригерит change, а поскольку логика enabled у разных компонентов может быть разная, то она реализуется непосредственно в компоненте

2021-05-13 16:52 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +        const buttons = step.get('buttons').map(
не понимаю, зачем

2021-05-14 08:54 UTC, vld-blv commented on src/layout/resources/wizard.css
> +.layout__wizard__header-view ul {
Это можно сделать на дивах вместо <ul><li></li></ul>, результат будет такой же, но просто для элементов, связанных с навигацией, обычно используют как раз ul

2021-05-14 11:13 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +        const stepModel = this.__stepsCollection.find(x => x.id === stepId);
Но это ведь не CollectionView, а просто Backbone.Collection

2021-05-17 08:46 UTC, vld-blv commented on src/layout/popup/PopupView.ts
> +            this.ui.window.css('background-color', this.options.backgroundColor);
Исправил

2021-05-17 08:46 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +        helpers.assertArgumentNotFalsy(stepId, 'stepId');
Убрал

2021-05-17 08:47 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +    async __generateButtonActions(step: Backbone.Model) {
Убрал

2021-05-17 08:47 UTC, vld-blv commented on src/layout/resources/wizard.css
> +    background-color: #f5f5f5;
Сделал все цвета, что есть в темах, из темы

2021-05-17 08:48 UTC, vld-blv commented on src/layout/wizard/WizardHeaderItemView.ts
> +// @flow
Убрал

2021-05-17 08:48 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +        const classList = [];
Исправил

2021-05-17 08:59 UTC, vld-blv commented on src/layout/resources/wizard.css
> +    align-self: unset !important;
В файле theme.css в коре есть такой стиль
![image](https://user-images.githubusercontent.com/55315304/118461527-6fe69000-b706-11eb-8cb8-df6e1736e22b.png)
Странность в том, что когда я в этом месте изменил baseline на center, все равно почему-то остается baseline
А в девтулзах показано, что стиль берется не из коры, а из продукта, хотя в продукте такого стиля нет
![image](https://user-images.githubusercontent.com/55315304/118462312-35c9be00-b707-11eb-8005-4117dc4a2a01.png)

Поэтому я явно перезаписал стили конкретно для визарда через important

2021-05-17 13:20 UTC, vld-blv commented on src/layout/resources/wizard.css
> +    transform: skewX(-35deg);
С 9 версии поддерживается

2021-05-17 13:21 UTC, vld-blv commented on src/layout/wizard/WizardHeaderItemView.ts
> +        this.el.setAttribute('id', this.model.id);
Их убрал

2021-05-17 13:27 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +                stepModel.set('__visible', stepModel.get('visible')());
Здесь так странно, потому что нужно динамически высчитывать значение свойства и поэтому не могу перезаписывать приходящее изначально свойство.
Можно было еще перенести сюда из WizardHeaderItemView применение класса к элементу, но я выбрал этот вариант, чтобы не разносить применение классов в разные места

2021-05-19 13:27 UTC, stasguryev commented on src/layout/wizard/WizardView.ts
> +            this.trigger(...args);
step

2021-05-19 13:29 UTC, stasguryev commented on src/layout/wizard/WizardView.ts
> +            this.listenTo(step.get('view').model, 'change', () => {
update должен происходить в момент update всего WizardView

2021-05-20 15:35 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +            this.trigger(...args);
триггеры нигде не слушаются, убрал это

2021-05-20 15:36 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +            this.listenTo(step.get('view').model, 'change', () => {
Ну конкретно для кнопок наверное все же не нужно обновлять весь визард

2021-05-26 09:36 UTC, stasguryev commented on src/layout/popup/PopupView.ts
> +            customClass: this.options.class || '',
windowClass или через модификатор

2021-05-26 14:17 UTC, pablo3443 requested changes

2021-05-26 14:17 UTC, pablo3443 commented on src/layout/button/ButtonView.js
> +            this.handlerResult = this.options.handler(this.options.context);
почему нельзя просто вызвать без handlerResult

2021-05-26 14:17 UTC, pablo3443 commented on src/layout/wizard/WizardView.ts
> +        return new Core.layout.HorizontalLayout({
используй Core.toolbar
там будет проще и понятнее

2021-05-27 08:26 UTC, vld-blv commented on src/layout/button/ButtonView.js
> +            this.handlerResult = this.options.handler(this.options.context);
В визарде нужно получать результат хендлера. А его вызов происходит в другом месте - во вьюхе кнопки. Если вызывать хендлер в визарде, то получится 2 вызова, поэтому я в самой кнопке фиксирую результат выполнения хендлера и потом с ним работаю. Лучшего решения не нашел

2021-05-28 12:18 UTC, vld-blv commented on src/layout/popup/PopupView.ts
> +            customClass: this.options.class || '',
сделал windowClass

2021-05-28 12:20 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +        return new Core.layout.HorizontalLayout({
оставил так, потому что тулбар создает 3 региона, из которых использоваться всегда будет один, и дополнительную вложенность в этих регионах
![image](https://user-images.githubusercontent.com/55315304/119982937-2a5c7980-bfc8-11eb-9096-10561b929b8d.png)

2021-05-31 08:33 UTC, stasguryev commented on src/layout/popup/PopupView.ts
> +            windowClass: this.options.class || '',
this.options.windowClass

2021-05-31 08:33 UTC, stasguryev commented on src/layout/button/ButtonView.js
> +        return `${classes.CLASS_NAME} ${this.options.alignClass || ''}`;
alignClass => this.options.class

2021-05-31 08:39 UTC, stasguryev commented on src/layout/wizard/WizardView.ts
> +        if (previousStep) {
move to 157 line

2021-05-31 08:41 UTC, stasguryev commented on src/layout/wizard/WizardView.ts
> +            Core.InterfaceError.logError('stepsCollection must be passed');
Steps collection

2021-05-31 09:11 UTC, stasguryev commented on src/layout/wizard/WizardView.ts
> +            buttons: { el: buttonsRegionEl }
dynamic name?

2021-05-31 13:28 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +            buttons: { el: buttonsRegionEl }
исправил

2021-05-31 13:28 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +            Core.InterfaceError.logError('stepsCollection must be passed');
исправил

2021-05-31 13:28 UTC, vld-blv commented on src/layout/wizard/WizardView.ts
> +        if (previousStep) {
исправил

2021-05-31 13:28 UTC, vld-blv commented on src/layout/button/ButtonView.js
> +        return `${classes.CLASS_NAME} ${this.options.alignClass || ''}`;
исправил

2021-05-31 13:28 UTC, vld-blv commented on src/layout/popup/PopupView.ts
> +            windowClass: this.options.class || '',
исправил

2021-06-01 10:10 UTC, merged