[#664980] Add uri attribute
comindware/core-ui pull request #1617
Opened 2021-07-18 14:27 UTC by Tonypz

![image](https://user-images.githubusercontent.com/23166800/126070905-e1d70549-764a-43b3-899c-b418aa809e5b.png)
![image](https://user-images.githubusercontent.com/23166800/126070921-800a92f7-00e5-444f-af70-380a23dc4028.png)
![image](https://user-images.githubusercontent.com/23166800/126070929-b0bb37c7-b859-411d-92c8-f7540777667e.png)

2021-07-23 14:13 UTC, pablo3443 requested changes

2021-07-23 14:13 UTC, pablo3443 commented on src/form/validators/sshValidator.ts
> +            message: LocalizationService.get('CORE.FORM.EDITORS.URIEDITOR.MSGVALIDATORTELEGRAM')
!

2021-07-23 14:13 UTC, pablo3443 commented on src/form/validators/mailtoValidator.ts
> +        if (!/@/.test(value)) {
!

2021-07-23 14:13 UTC, pablo3443 commented on src/form/editors/templates/uriEditor.hbs
> +    <input type="{{type}}" class="uri-input js-input" {{#if maxLength}}maxlength="{{maxLength}}"{{/if}} {{#if fieldId}} id="{{fieldId}} {{/if}}">
js-класс первым

2021-07-23 14:13 UTC, pablo3443 commented on src/form/editors/base/MarionetteEditorPrototype.ts
> +            if (this.options.type === 'Uri' && validators.length > errors.length) {
убрать !!!!!

2021-07-23 14:13 UTC, pablo3443 commented on src/form/editors/UriEditorView.js
> +            case 'phone': {
мета

2021-07-23 14:13 UTC, pablo3443 commented on src/form/editors/UriEditorView.js
> +        this.ui.link[0].setAttribute('href', this.__getHrefFormat(this.validatorOptions));
тип должен быть не в опцях валидатора, а в общих

2021-07-23 14:14 UTC, pablo3443 commented on src/form/validators/mailtoValidator.ts
> +        if (!/@/.test(value)) {
проверка так себе

2021-07-23 16:43 UTC, Tonypz commented on src/form/validators/sshValidator.ts
> +            message: LocalizationService.get('CORE.FORM.EDITORS.URIEDITOR.MSGVALIDATORTELEGRAM')
done

2021-07-23 16:43 UTC, Tonypz commented on src/form/editors/templates/uriEditor.hbs
> +    <input type="{{type}}" class="uri-input js-input" {{#if maxLength}}maxlength="{{maxLength}}"{{/if}} {{#if fieldId}} id="{{fieldId}} {{/if}}">
done

2021-07-23 16:52 UTC, Tonypz commented on src/form/editors/base/MarionetteEditorPrototype.ts
> +            if (this.options.type === 'Uri' && validators.length > errors.length) {
don

2021-07-24 09:39 UTC, stasguryev commented on src/form/editors/UriEditorView.js
> + * @class Преобразователь текстовой строки в сслку. Поддерживаемый тип входных данных: <code>String</code>.
in English please

2021-07-24 09:39 UTC, stasguryev commented on src/form/editors/UriEditorView.js
> +    validate() {
why override?

2021-07-24 09:39 UTC, stasguryev commented on src/form/editors/base/MarionetteEditorPrototype.ts
> +            let errors: Array<Object> = [];
revert

2021-07-24 09:39 UTC, stasguryev commented on src/form/formRepository.ts
> +import Http from './validators/httpValidator';
RegExpValidator

2021-07-25 10:18 UTC, closed without merging

2021-07-25 10:18 UTC, Tonypz commented
without merge