[#973025] Fix displaying enabled tabs in atribute popup
comindware/core-ui pull request #1654
Opened 2021-09-02 08:24 UTC by GuliyanK

2021-09-06 12:09 UTC, pablo3443 requested changes

2021-09-06 12:09 UTC, pablo3443 commented on src/layout/tabLayout/TabLayoutView.ts
>  import ConfigDiff from '../../components/treeEditor/classes/ConfigDiff';
нужно зааплайить LayoutBehavior на отдельную табу
убрать фнукции setEnabled, setVisible и все лишнее
сделать так чтобы во вьюхе табы на апдейт просходил updateState

2021-09-06 12:09 UTC, pablo3443 commented on src/layout/tabLayout/TabLayoutView.ts
> +type Tab = { view: Backbone.View, id: string, name: string, enabled?: any, visible?: boolean, error?: string };
вместо any можно указать два типа

2021-09-06 12:09 UTC, pablo3443 commented on src/layout/tabLayout/TabLayoutView.ts
>  import ConfigDiff from '../../components/treeEditor/classes/ConfigDiff';
в продукте можно либо заменить голые вкладки на форму
либо на изменение использовать функцию tabLayout.update()

2021-09-07 11:46 UTC, stasguryev commented on src/layout/tabLayout/TabLayoutView.ts
> +        this.listenTo(view, 'change:enabled', (model, enabled) => this.setEnabled(tabModel.id, tabModel.get('enableCondition') ?? tabModel.get('enabled')));
enableCondition ?

2021-11-10 16:24 UTC, closed without merging